In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle("05疑似個人情報.pkl")

In [3]:
df.shape

(50, 9)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
連番          50 non-null int64
氏名          50 non-null object
氏名（カタカナ）    50 non-null object
性別          50 non-null object
電話番号        50 non-null int64
生年月日        50 non-null object
年齢          50 non-null int64
出身地         50 non-null object
血液型         50 non-null object
dtypes: int64(3), object(6)
memory usage: 3.6+ KB

In [5]:
df.head()

   連番    氏名 氏名（カタカナ） 性別       電話番号        生年月日  年齢  出身地 血液型
0   1  大高睦美  オオダカムツミ  女  832236710  1986/04/09  33  沖縄県   O
1   2  沢井博一  サワイヒロカズ  男  981799985  1993/09/16  26  三重県   O
2   3  島崎繁雄  シマザキシゲオ  男  868036734  1972/10/17  47  佐賀県   A
3   4   乾孝二   イヌイコウジ  男  842103869  1968/05/12  51  北海道   A
4   5   恩田希   オンダノゾミ  女  294460772  1994/06/04  25  滋賀県   A

In [6]:
# 生年月日をto_datetime()
df["生年月日"] = pd.to_datetime(df["生年月日"])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
連番          50 non-null int64
氏名          50 non-null object
氏名（カタカナ）    50 non-null object
性別          50 non-null object
電話番号        50 non-null int64
生年月日        50 non-null datetime64[ns]
年齢          50 non-null int64
出身地         50 non-null object
血液型         50 non-null object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 3.6+ KB

In [8]:
# 1985年以降生まれの女性
df.loc[(df["性別"] == "女") & (df["生年月日"].dt.year >= 1985), :]
# df["生年月日"] >= "1985" 文字列でもいける

    連番     氏名  氏名（カタカナ） 性別       電話番号       生年月日  年齢  出身地 血液型
0    1   大高睦美   オオダカムツミ  女  832236710 1986-04-09  33  沖縄県   O
4    5    恩田希    オンダノゾミ  女  294460772 1994-06-04  25  滋賀県   A
14  15   大山祥子  オオヤマショウコ  女  948739566 1987-05-05  32  岡山県   A
15  16   市村杏奈   イチムラアンナ  女  461715578 1987-11-28  32  長野県  AB
16  17   安斉春花   アンザイハルカ  女  243403918 1985-05-28  34  愛知県   A
21  22   立川愛結    タチカワアユ  女  963464213 1999-12-20  20  石川県   A
31  32   南古都子    ミナミコトコ  女  942880024 2000-01-19  20  新潟県   A
38  39   浅野小絵     アサノサエ  女  770395477 1997-09-26  22  沖縄県   O
43  44  大江千加子    オオエチカコ  女  602267293 1990-09-04  29  広島県   O
44  45  諏訪千代乃     スワチヨノ  女  886023497 1985-04-20  34  三重県   O
45  46    日野薫     ヒノカオル  女  966489373 1995-06-24  24  岩手県   B
48  49   門田志帆     カドタシホ  女   27969750 1996-06-23  23  山口県   O

In [9]:
# 4月生まれ女性
df.loc[(df["性別"] == "女") & (df["生年月日"].dt.month == 4), :]

    連番     氏名 氏名（カタカナ） 性別       電話番号       生年月日  年齢  出身地 血液型
0    1   大高睦美  オオダカムツミ  女  832236710 1986-04-09  33  沖縄県   O
25  26   長田風花   ナガタフウカ  女  768425215 1976-04-21  43  秋田県   O
44  45  諏訪千代乃    スワチヨノ  女  886023497 1985-04-20  34  三重県   O

In [10]:
# A型の男性
df.loc[(df["性別"] == "男") & (df["血液型"] == "A"), :]

    連番     氏名  氏名（カタカナ） 性別       電話番号       生年月日  年齢  出身地 血液型
2    3   島崎繁雄   シマザキシゲオ  男  868036734 1972-10-17  47  佐賀県   A
3    4    乾孝二    イヌイコウジ  男  842103869 1968-05-12  51  北海道   A
5    6   神保徳康   ジンボトクヤス  男  979259707 1962-05-08  57  新潟県   A
6    7   西野匠音    ニシノシオン  男  172679867 1967-03-07  52  北海道   A
9   10   富沢敏彦  トミザワトシヒコ  男  858732938 1984-07-17  35  新潟県   A
10  11   平野裕之   ヒラノヒロユキ  男  952170680 1979-06-12  40  千葉県   A
20  21   麻生隆一  アソウリュウイチ  男  773761182 1973-10-27  46  宮崎県   A
23  24   山形常吉  ヤマガタツネキチ  男  251614437 1977-09-29  42  愛媛県   A
24  25  菊池健次郎  キクチケンジロウ  男   22047918 1986-10-08  33  秋田県   A
27  28   堀越文翔   ホリコシフミト  男  942292471 1999-01-14  21  岡山県   A
34  35   恩田幸真   オンダユキマサ  男   27609522 1974-03-14  45  京都府   A
37  38   太田慎一   オオタシンイチ  男  117693297 1992-12-21  27  兵庫県   A
41  42    上野淳    アガノアツシ  男  740354044 1987-06-05  32  島根県   A

In [11]:
# 出身地 北海道をほっかいどうに置換
df.loc[df["出身地"] == "北海道", "出身地"] = "ほっかいどう"
df

    連番     氏名  氏名（カタカナ） 性別       電話番号       生年月日  年齢     出身地 血液型
0    1   大高睦美   オオダカムツミ  女  832236710 1986-04-09  33     沖縄県   O
1    2   沢井博一   サワイヒロカズ  男  981799985 1993-09-16  26     三重県   O
2    3   島崎繁雄   シマザキシゲオ  男  868036734 1972-10-17  47     佐賀県   A
3    4    乾孝二    イヌイコウジ  男  842103869 1968-05-12  51  ほっかいどう   A
4    5    恩田希    オンダノゾミ  女  294460772 1994-06-04  25     滋賀県   A
5    6   神保徳康   ジンボトクヤス  男  979259707 1962-05-08  57     新潟県   A
6    7   西野匠音    ニシノシオン  男  172679867 1967-03-07  52  ほっかいどう   A
7    8   小室竜也    コムロタツヤ  男  992234443 1984-04-22  35     茨城県   O
8    9    大田実    オオタミノル  男  296848184 1961-09-03  58     茨城県  AB
9   10   富沢敏彦  トミザワトシヒコ  男  858732938 1984-07-17  35     新潟県   A
10  11   平野裕之   ヒラノヒロユキ  男  952170680 1979-06-12  40     千葉県   A
11  12   内海瑠奈     ウツミルナ  女  986743368 1962-06-27  57     京都府   O
12  13    辻定男     ツジサダオ  男  446115933 1974-03-06  45     長崎県   O
13  14   三島瑠衣     ミシマルイ  女   93947108 1963-06-18  56     東京都   B
14  15   大山祥子  オオヤマショウコ  女  948739566 1987-05-05  32     岡山県   A
15  16   市村杏奈   イチムラアンナ  女  461715578 1987-11-28  32     長野県  AB
16  17   安斉春花   アンザイハルカ  女  243403918 1985-05-28  34     愛知県   A
17  18   野呂広史     ノロヒロシ  男  888587846 1964-04-20  55    和歌山県   B
18  19   岩本羽菜    イワモトハナ  女  966521557 1978-02-17  41  ほっかいどう  AB
19  20  東海林勇雄   ショウジイサオ  男  190410166 1990-03-08  29     埼玉県   O
20  21   麻生隆一  アソウリュウイチ  男  773761182 1973-10-27  46     宮崎県   A
21  22   立川愛結    タチカワアユ  女  963464213 1999-12-20  20     石川県   A
22  23   町田重彦   マチダシゲヒコ  男  885022251 1975-11-25  44     熊本県   B
23  24   山形常吉  ヤマガタツネキチ  男  251614437 1977-09-29  42     愛媛県   A
24  25  菊池健次郎  キクチケンジロウ  男   22047918 1986-10-08  33     秋田県   A
25  26   長田風花    ナガタフウカ  女  768425215 1976-04-21  43     秋田県   O
26  27   杉田雅康   スギタマサヤス  男  881943162 1964-11-14  55     三重県   O
27  28   堀越文翔   ホリコシフミト  男  942292471 1999-01-14  21     岡山県   A
28  29   土谷沙樹     ツチヤサキ  女  277008054 1964-10-30  55     秋田県   A
29  30   志賀航太     シガコウタ  男  550273438 1999-08-16  20     埼玉県   O
30  31    藤谷蓮    フジタニレン  女  824039378 1975-11-27  44     静岡県   A
31  32   南古都子    ミナミコトコ  女  942880024 2000-01-19  20     新潟県   A
32  33   畠山佳子  ハタケヤマヨシコ  女  723262077 1962-11-25  57     石川県   A
33  34  村山沙耶香   ムラヤマサヤカ  女  886246810 1980-11-06  39     長崎県   O
34  35   恩田幸真   オンダユキマサ  男   27609522 1974-03-14  45     京都府   A
35  36   梶原六郎  カジワラロクロウ  男  489582454 1979-08-30  40     福島県   O
36  37  松島日花里   マツシマヒカリ  女  176088633 1974-09-17  45     大阪府   B
37  38   太田慎一   オオタシンイチ  男  117693297 1992-12-21  27     兵庫県   A
38  39   浅野小絵     アサノサエ  女  770395477 1997-09-26  22     沖縄県   O
39  40   水口公子   ミズグチキミコ  女  488473758 1983-03-11  36     石川県   A
40  41    松木恵     マツキケイ  女  849352817 1962-11-19  57     山口県   A
41  42    上野淳    アガノアツシ  男  740354044 1987-06-05  32     島根県   A
42  43   川畑政昭  カワバタマサアキ  男  833312321 1987-09-15  32     石川県   B
43  44  大江千加子    オオエチカコ  女  602267293 1990-09-04  29     広島県   O
44  45  諏訪千代乃     スワチヨノ  女  886023497 1985-04-20  34     三重県   O
45  46    日野薫     ヒノカオル  女  966489373 1995-06-24  24     岩手県   B
46  47   上岡涼太  カミオカリョウタ  男   94801791 1979-10-10  40     東京都   O
47  48   大倉利雄   オオクラトシオ  男  983089261 1984-08-18  35    和歌山県   B
48  49   門田志帆     カドタシホ  女   27969750 1996-06-23  23     山口県   O
49  50   仲村有沙   ナカムラアリサ  女  433504261 1974-07-27  45     広島県   A

In [12]:
# 出身地の種類
df["出身地"].value_counts()

石川県       4
ほっかいどう    3
新潟県       3
三重県       3
秋田県       3
沖縄県       2
埼玉県       2
長崎県       2
広島県       2
山口県       2
京都府       2
茨城県       2
岡山県       2
和歌山県      2
東京都       2
愛媛県       1
熊本県       1
宮崎県       1
島根県       1
福島県       1
千葉県       1
兵庫県       1
滋賀県       1
岩手県       1
佐賀県       1
大阪府       1
静岡県       1
愛知県       1
長野県       1
Name: 出身地, dtype: int64

In [13]:
# 血液型の割合
df["血液型"].value_counts(normalize=True)

A     0.48
O     0.32
B     0.14
AB    0.06
Name: 血液型, dtype: float64

In [14]:
# 男女比
df["性別"].value_counts(normalize=True)

男    0.52
女    0.48
Name: 性別, dtype: float64

In [15]:
# 年齢の平均
df["年齢"].mean()

38.9

In [16]:
# 年齢の最小
df["年齢"].min()

20

In [17]:
# 年齢の最大
df["年齢"].max()

58

In [18]:
# 年代カラムを作成
df["年代"] = pd.cut(df["年齢"], [0, 10, 20, 30, 40 ,50 ,60])
df.head()

   連番    氏名 氏名（カタカナ） 性別       電話番号       生年月日  年齢     出身地 血液型        年代
0   1  大高睦美  オオダカムツミ  女  832236710 1986-04-09  33     沖縄県   O  (30, 40]
1   2  沢井博一  サワイヒロカズ  男  981799985 1993-09-16  26     三重県   O  (20, 30]
2   3  島崎繁雄  シマザキシゲオ  男  868036734 1972-10-17  47     佐賀県   A  (40, 50]
3   4   乾孝二   イヌイコウジ  男  842103869 1968-05-12  51  ほっかいどう   A  (50, 60]
4   5   恩田希   オンダノゾミ  女  294460772 1994-06-04  25     滋賀県   A  (20, 30]

In [19]:
# 年代、血液型をグループ化
g = df.groupby(["年代","血液型"])

In [20]:
g["血液型"].count()

年代        血液型
(10, 20]  A      2
          O      1
(20, 30]  A      3
          B      1
          O      5
(30, 40]  A      7
          AB     1
          B      2
          O      6
(40, 50]  A      6
          AB     1
          B      2
          O      2
(50, 60]  A      6
          AB     1
          B      2
          O      2
Name: 血液型, dtype: int64

In [21]:
# 性別と血液型をダミー変数
df = pd.get_dummies(df, columns=["性別", "血液型"])
df

,連番,氏名,氏名（カタカナ）,電話番号,生年月日,年齢,出身地,年代,性別_女,性別_男,血液型_A,血液型_AB,血液型_B,血液型_O
0,1,大高睦美,オオダカムツミ,832236710,1986-04-09,33,沖縄県,"(30, 40]",1,0,0,0,0,1
1,2,沢井博一,サワイヒロカズ,981799985,1993-09-16,26,三重県,"(20, 30]",0,1,0,0,0,1
2,3,島崎繁雄,シマザキシゲオ,868036734,1972-10-17,47,佐賀県,"(40, 50]",0,1,1,0,0,0
3,4,乾孝二,イヌイコウジ,842103869,1968-05-12,51,ほっかいどう,"(50, 60]",0,1,1,0,0,0
4,5,恩田希,オンダノゾミ,294460772,1994-06-04,25,滋賀県,"(20, 30]",1,0,1,0,0,0
5,6,神保徳康,ジンボトクヤス,979259707,1962-05-08,57,新潟県,"(50, 60]",0,1,1,0,0,0
6,7,西野匠音,ニシノシオン,172679867,1967-03-07,52,ほっかいどう,"(50, 60]",0,1,1,0,0,0
7,8,小室竜也,コムロタツヤ,992234443,1984-04-22,35,茨城県,"(30, 40]",0,1,0,0,0,1
8,9,大田実,オオタミノル,296848184,1961-09-03,58,茨城県,"(50, 60]",0,1,0,1,0,0
9,10,富沢敏彦,トミザワトシヒコ,858732938,1984-07-17,35,新潟県,"(30, 40]",0,1,1,0,0,0
10,11,平野裕之,ヒラノヒロユキ,952170680,1979-06-12,40,千葉県,"(30, 40]",0,1,1,0,0,0
11,12,内海瑠奈,ウツミルナ,986743368,1962-06-27,57,京都府,"(50, 60]",1,0,0,0,0,1
12,13,辻定男,ツジサダオ,446115933,1974-03-06,45,長崎県,"(40, 50]",0,1,0,0,0,1
13,14,三島瑠衣,ミシマルイ,93947108,1963-06-18,56,東京都,"(50, 60]",1,0,0,0,1,0
14,15,大山祥子,オオヤマショウコ,948739566,1987-05-05,32,岡山県,"(30, 40]",1,0,1,0,0,0
15,16,市村杏奈,イチムラアンナ,461715578,1987-11-28,32,長野県,"(30, 40]",1,0,0,1,0,0
16,17,安斉春花,アンザイハルカ,243403918,1985-05-28,34,愛知県,"(30, 40]",1,0,1,0,0,0
17,18,野呂広史,ノロヒロシ,888587846,1964-04-20,55,和歌山県,"(50, 60]",0,1,0,0,1,0
18,19,岩本羽菜,イワモトハナ,966521557,1978-02-17,41,ほっかいどう,"(40, 50]",1,0,0,1,0,0
19,20,東海林勇雄,ショウジイサオ,190410166,1990-03-08,29,埼玉県,"(20, 30]",0,1,0,0,0,1
20,21,麻生隆一,アソウリュウイチ,773761182,1973-10-27,46,宮崎県,"(40, 50]",0,1,1,0,0,0
21,22,立川愛結,タチカワアユ,963464213,1999-12-20,20,石川県,"(10, 20]",1,0,1,0,0,0
22,23,町田重彦,マチダシゲヒコ,885022251,1975-11-25,44,熊本県,"(40, 50]",0,1,0,0,1,0
23,24,山形常吉,ヤマガタツネキチ,251614437,1977-09-29,42,愛媛県,"(40, 50]",0,1,1,0,0,0
24,25,菊池健次郎,キクチケンジロウ,22047918,1986-10-08,33,秋田県,"(30, 40]",0,1,1,0,0,0
25,26,長田風花,ナガタフウカ,768425215,1976-04-21,43,秋田県,"(40, 50]",1,0,0,0,0,1
26,27,杉田雅康,スギタマサヤス,881943162,1964-11-14,55,三重県,"(50, 60]",0,1,0,0,0,1
27,28,堀越文翔,ホリコシフミト,942292471,1999-01-14,21,岡山県,"(20, 30]",0,1,1,0,0,0
28,29,土谷沙樹,ツチヤサキ,277008054,1964-10-30,55,秋田県,"(50, 60]",1,0,1,0,0,0
29,30,志賀航太,シガコウタ,550273438,1999-08-16,20,埼玉県,"(10, 20]",0,1,0,0,0,1
30,31,藤谷蓮,フジタニレン,824039378,1975-11-27,44,静岡県,"(40, 50]",1,0,1,0,0,0
31,32,南古都子,ミナミコトコ,942880024,2000-01-19,20,新潟県,"(10, 20]",1,0,1,0,0,0
32,33,畠山佳子,ハタケヤマヨシコ,723262077,1962-11-25,57,石川県,"(50, 60]",1,0,1,0,0,0
33,34,村山沙耶香,ムラヤマサヤカ,886246810,1980-11-06,39,長崎県,"(30, 40]",1,0,0,0,0,1
34,35,恩田幸真,オンダユキマサ,27609522,1974-03-14,45,京都府,"(40, 50]",0,1,1,0,0,0
35,36,梶原六郎,カジワラロクロウ,489582454,1979-08-30,40,福島県,"(30, 40]",0,1,0,0,0,1
36,37,松島日花里,マツシマヒカリ,176088633,1974-09-17,45,大阪府,"(40, 50]",1,0,0,0,1,0
37,38,太田慎一,オオタシンイチ,117693297,1992-12-21,27,兵庫県,"(20, 30]",0,1,1,0,0,0
38,39,浅野小絵,アサノサエ,770395477,1997-09-26,22,沖縄県,"(20, 30]",1,0,0,0,0,1
39,40,水口公子,ミズグチキミコ,488473758,1983-03-11,36,石川県,"(30, 40]",1,0,1,0,0,0
40,41,松木恵,マツキケイ,849352817,1962-11-19,57,山口県,"(50, 60]",1,0,1,0,0,0
41,42,上野淳,アガノアツシ,740354044,1987-06-05,32,島根県,"(30, 40]",0,1,1,0,0,0
42,43,川畑政昭,カワバタマサアキ,833312321,1987-09-15,32,石川県,"(30, 40]",0,1,0,0,1,0
43,44,大江千加子,オオエチカコ,602267293,1990-09-04,29,広島県,"(20, 30]",1,0,0,0,0,1
44,45,諏訪千代乃,スワチヨノ,886023497,1985-04-20,34,三重県,"(30, 40]",1,0,0,0,0,1
45,46,日野薫,ヒノカオル,966489373,1995-06-24,24,岩手県,"(20, 30]",1,0,0,0,1,0
46,47,上岡涼太,カミオカリョウタ,94801791,1979-10-10,40,東京都,"(30, 40]",0,1,0,0,0,1
47,48,大倉利雄,オオクラトシオ,983089261,1984-08-18,35,和歌山県,"(30, 40]",0,1,0,0,1,0
48,49,門田志帆,カドタシホ,27969750,1996-06-23,23,山口県,"(20, 30]",1,0,0,0,0,1
49,50,仲村有沙,ナカムラアリサ,433504261,1974-07-27,45,広島県,"(40, 50]",1,0,1,0,0,0

In [22]:
# カタカナにアがつく人はカラム「ア」に1
df["ア"] = 0

In [23]:
df.loc[df["氏名（カタカナ）"].str.contains("ア"), "ア"] = 1

In [24]:
df

,連番,氏名,氏名（カタカナ）,電話番号,生年月日,年齢,出身地,年代,性別_女,性別_男,血液型_A,血液型_AB,血液型_B,血液型_O,ア
0,1,大高睦美,オオダカムツミ,832236710,1986-04-09,33,沖縄県,"(30, 40]",1,0,0,0,0,1,0
1,2,沢井博一,サワイヒロカズ,981799985,1993-09-16,26,三重県,"(20, 30]",0,1,0,0,0,1,0
2,3,島崎繁雄,シマザキシゲオ,868036734,1972-10-17,47,佐賀県,"(40, 50]",0,1,1,0,0,0,0
3,4,乾孝二,イヌイコウジ,842103869,1968-05-12,51,ほっかいどう,"(50, 60]",0,1,1,0,0,0,0
4,5,恩田希,オンダノゾミ,294460772,1994-06-04,25,滋賀県,"(20, 30]",1,0,1,0,0,0,0
5,6,神保徳康,ジンボトクヤス,979259707,1962-05-08,57,新潟県,"(50, 60]",0,1,1,0,0,0,0
6,7,西野匠音,ニシノシオン,172679867,1967-03-07,52,ほっかいどう,"(50, 60]",0,1,1,0,0,0,0
7,8,小室竜也,コムロタツヤ,992234443,1984-04-22,35,茨城県,"(30, 40]",0,1,0,0,0,1,0
8,9,大田実,オオタミノル,296848184,1961-09-03,58,茨城県,"(50, 60]",0,1,0,1,0,0,0
9,10,富沢敏彦,トミザワトシヒコ,858732938,1984-07-17,35,新潟県,"(30, 40]",0,1,1,0,0,0,0
10,11,平野裕之,ヒラノヒロユキ,952170680,1979-06-12,40,千葉県,"(30, 40]",0,1,1,0,0,0,0
11,12,内海瑠奈,ウツミルナ,986743368,1962-06-27,57,京都府,"(50, 60]",1,0,0,0,0,1,0
12,13,辻定男,ツジサダオ,446115933,1974-03-06,45,長崎県,"(40, 50]",0,1,0,0,0,1,0
13,14,三島瑠衣,ミシマルイ,93947108,1963-06-18,56,東京都,"(50, 60]",1,0,0,0,1,0,0
14,15,大山祥子,オオヤマショウコ,948739566,1987-05-05,32,岡山県,"(30, 40]",1,0,1,0,0,0,0
15,16,市村杏奈,イチムラアンナ,461715578,1987-11-28,32,長野県,"(30, 40]",1,0,0,1,0,0,1
16,17,安斉春花,アンザイハルカ,243403918,1985-05-28,34,愛知県,"(30, 40]",1,0,1,0,0,0,1
17,18,野呂広史,ノロヒロシ,888587846,1964-04-20,55,和歌山県,"(50, 60]",0,1,0,0,1,0,0
18,19,岩本羽菜,イワモトハナ,966521557,1978-02-17,41,ほっかいどう,"(40, 50]",1,0,0,1,0,0,0
19,20,東海林勇雄,ショウジイサオ,190410166,1990-03-08,29,埼玉県,"(20, 30]",0,1,0,0,0,1,0
20,21,麻生隆一,アソウリュウイチ,773761182,1973-10-27,46,宮崎県,"(40, 50]",0,1,1,0,0,0,1
21,22,立川愛結,タチカワアユ,963464213,1999-12-20,20,石川県,"(10, 20]",1,0,1,0,0,0,1
22,23,町田重彦,マチダシゲヒコ,885022251,1975-11-25,44,熊本県,"(40, 50]",0,1,0,0,1,0,0
23,24,山形常吉,ヤマガタツネキチ,251614437,1977-09-29,42,愛媛県,"(40, 50]",0,1,1,0,0,0,0
24,25,菊池健次郎,キクチケンジロウ,22047918,1986-10-08,33,秋田県,"(30, 40]",0,1,1,0,0,0,0
25,26,長田風花,ナガタフウカ,768425215,1976-04-21,43,秋田県,"(40, 50]",1,0,0,0,0,1,0
26,27,杉田雅康,スギタマサヤス,881943162,1964-11-14,55,三重県,"(50, 60]",0,1,0,0,0,1,0
27,28,堀越文翔,ホリコシフミト,942292471,1999-01-14,21,岡山県,"(20, 30]",0,1,1,0,0,0,0
28,29,土谷沙樹,ツチヤサキ,277008054,1964-10-30,55,秋田県,"(50, 60]",1,0,1,0,0,0,0
29,30,志賀航太,シガコウタ,550273438,1999-08-16,20,埼玉県,"(10, 20]",0,1,0,0,0,1,0
30,31,藤谷蓮,フジタニレン,824039378,1975-11-27,44,静岡県,"(40, 50]",1,0,1,0,0,0,0
31,32,南古都子,ミナミコトコ,942880024,2000-01-19,20,新潟県,"(10, 20]",1,0,1,0,0,0,0
32,33,畠山佳子,ハタケヤマヨシコ,723262077,1962-11-25,57,石川県,"(50, 60]",1,0,1,0,0,0,0
33,34,村山沙耶香,ムラヤマサヤカ,886246810,1980-11-06,39,長崎県,"(30, 40]",1,0,0,0,0,1,0
34,35,恩田幸真,オンダユキマサ,27609522,1974-03-14,45,京都府,"(40, 50]",0,1,1,0,0,0,0
35,36,梶原六郎,カジワラロクロウ,489582454,1979-08-30,40,福島県,"(30, 40]",0,1,0,0,0,1,0
36,37,松島日花里,マツシマヒカリ,176088633,1974-09-17,45,大阪府,"(40, 50]",1,0,0,0,1,0,0
37,38,太田慎一,オオタシンイチ,117693297,1992-12-21,27,兵庫県,"(20, 30]",0,1,1,0,0,0,0
38,39,浅野小絵,アサノサエ,770395477,1997-09-26,22,沖縄県,"(20, 30]",1,0,0,0,0,1,1
39,40,水口公子,ミズグチキミコ,488473758,1983-03-11,36,石川県,"(30, 40]",1,0,1,0,0,0,0
40,41,松木恵,マツキケイ,849352817,1962-11-19,57,山口県,"(50, 60]",1,0,1,0,0,0,0
41,42,上野淳,アガノアツシ,740354044,1987-06-05,32,島根県,"(30, 40]",0,1,1,0,0,0,1
42,43,川畑政昭,カワバタマサアキ,833312321,1987-09-15,32,石川県,"(30, 40]",0,1,0,0,1,0,1
43,44,大江千加子,オオエチカコ,602267293,1990-09-04,29,広島県,"(20, 30]",1,0,0,0,0,1,0
44,45,諏訪千代乃,スワチヨノ,886023497,1985-04-20,34,三重県,"(30, 40]",1,0,0,0,0,1,0
45,46,日野薫,ヒノカオル,966489373,1995-06-24,24,岩手県,"(20, 30]",1,0,0,0,1,0,0
46,47,上岡涼太,カミオカリョウタ,94801791,1979-10-10,40,東京都,"(30, 40]",0,1,0,0,0,1,0
47,48,大倉利雄,オオクラトシオ,983089261,1984-08-18,35,和歌山県,"(30, 40]",0,1,0,0,1,0,0
48,49,門田志帆,カドタシホ,27969750,1996-06-23,23,山口県,"(20, 30]",1,0,0,0,0,1,0
49,50,仲村有沙,ナカムラアリサ,433504261,1974-07-27,45,広島県,"(40, 50]",1,0,1,0,0,0,1