In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("head.csv")

In [3]:
df.head()

,レースID,年月日,レースNo,レース名,クラス,種別,距離,天候,状態,発走,競馬場,条件,Unnamed: 12
0,199901010611,1999年8月22日,11,第35回札幌記念,G2,芝右,2000,曇,良,15:35,1回札幌6日目,4歳以上オープン(混)(特指)(別定),NaN
1,199901020311,1999年9月11日,11,第4回エルムステークス,G3,ダ右,1700,曇,稍重,15:35,2回札幌3日目,4歳以上オープン(混)(指)(別定),NaN
2,199901020711,1999年9月25日,11,第34回札幌3歳ステークス,G3,芝右,1800,晴,重,15:50,2回札幌7日目,3歳オープン(混)(特指)(馬齢),NaN
3,199902010811,1999年7月4日,11,第35回函館記念,G3,芝右,2000,曇,良,15:35,1回函館8日目,4歳以上オープン(混)(特指)(ハンデ),NaN
4,199902020411,1999年7月18日,11,第6回函館スプリントS,G3,芝右,1200,晴,良,15:35,2回函館4日目,4歳以上オープン(混)(特指)(別定),NaN

In [4]:
df.drop(columns=["Unnamed: 12"], inplace=True)

In [5]:
df.head()

,レースID,年月日,レースNo,レース名,クラス,種別,距離,天候,状態,発走,競馬場,条件
0,199901010611,1999年8月22日,11,第35回札幌記念,G2,芝右,2000,曇,良,15:35,1回札幌6日目,4歳以上オープン(混)(特指)(別定)
1,199901020311,1999年9月11日,11,第4回エルムステークス,G3,ダ右,1700,曇,稍重,15:35,2回札幌3日目,4歳以上オープン(混)(指)(別定)
2,199901020711,1999年9月25日,11,第34回札幌3歳ステークス,G3,芝右,1800,晴,重,15:50,2回札幌7日目,3歳オープン(混)(特指)(馬齢)
3,199902010811,1999年7月4日,11,第35回函館記念,G3,芝右,2000,曇,良,15:35,1回函館8日目,4歳以上オープン(混)(特指)(ハンデ)
4,199902020411,1999年7月18日,11,第6回函館スプリントS,G3,芝右,1200,晴,良,15:35,2回函館4日目,4歳以上オープン(混)(特指)(別定)

In [6]:
df.isnull().sum()

レースID      0
年月日        0
レースNo      0
レース名       0
クラス      964
種別         0
距離         0
天候         0
状態         0
発走         0
競馬場        0
条件         0
dtype: int64

In [7]:
df["年月日"] = pd.to_datetime(df["年月日"], format='%Y年%m月%d日')

In [8]:
df.head()

,レースID,年月日,レースNo,レース名,クラス,種別,距離,天候,状態,発走,競馬場,条件
0,199901010611,1999-08-22,11,第35回札幌記念,G2,芝右,2000,曇,良,15:35,1回札幌6日目,4歳以上オープン(混)(特指)(別定)
1,199901020311,1999-09-11,11,第4回エルムステークス,G3,ダ右,1700,曇,稍重,15:35,2回札幌3日目,4歳以上オープン(混)(指)(別定)
2,199901020711,1999-09-25,11,第34回札幌3歳ステークス,G3,芝右,1800,晴,重,15:50,2回札幌7日目,3歳オープン(混)(特指)(馬齢)
3,199902010811,1999-07-04,11,第35回函館記念,G3,芝右,2000,曇,良,15:35,1回函館8日目,4歳以上オープン(混)(特指)(ハンデ)
4,199902020411,1999-07-18,11,第6回函館スプリントS,G3,芝右,1200,晴,良,15:35,2回函館4日目,4歳以上オープン(混)(特指)(別定)

In [9]:
# 名前付きグループ カラム名
df2 = df["競馬場"].str.extract('(?P<回数>\d*?)回(?P<場所>.*?)(?P<日程>\d.*)日', expand=True)

In [10]:
df2.head()

  回数  場所 日程
0  1  札幌  6
1  2  札幌  3
2  2  札幌  7
3  1  函館  8
4  2  函館  4

In [11]:
df = pd.concat([df, df2], axis=1)

In [12]:
df.head()

,レースID,年月日,レースNo,レース名,クラス,種別,距離,天候,状態,発走,競馬場,条件,回数,場所,日程
0,199901010611,1999-08-22,11,第35回札幌記念,G2,芝右,2000,曇,良,15:35,1回札幌6日目,4歳以上オープン(混)(特指)(別定),1,札幌,6
1,199901020311,1999-09-11,11,第4回エルムステークス,G3,ダ右,1700,曇,稍重,15:35,2回札幌3日目,4歳以上オープン(混)(指)(別定),2,札幌,3
2,199901020711,1999-09-25,11,第34回札幌3歳ステークス,G3,芝右,1800,晴,重,15:50,2回札幌7日目,3歳オープン(混)(特指)(馬齢),2,札幌,7
3,199902010811,1999-07-04,11,第35回函館記念,G3,芝右,2000,曇,良,15:35,1回函館8日目,4歳以上オープン(混)(特指)(ハンデ),1,函館,8
4,199902020411,1999-07-18,11,第6回函館スプリントS,G3,芝右,1200,晴,良,15:35,2回函館4日目,4歳以上オープン(混)(特指)(別定),2,函館,4

In [13]:
# 条件
df["条件"] = df["条件"].str.extract("(.*?)(\(|\[|$)")[0]

In [14]:
df["条件"].value_counts()

3歳以上オープン         914
4歳以上オープン         766
3歳オープン           554
2歳オープン           237
2歳未勝利            190
障害3歳以上オープン       139
3歳以上1勝クラス        136
2歳新馬             100
障害4歳以上オープン        79
3歳以上1000万下        67
3歳以上1600万下        53
3歳未勝利             48
3歳以上2勝クラス         45
4歳オープン            42
4歳以上1勝クラス         32
3歳以上1勝クラス牝        32
2歳未勝利牝            30
3歳オープン牡・牝         28
3歳オープン牝           25
2歳500万下           24
3歳以上500万下         22
障害3歳以上未勝利         21
3歳新馬              16
3歳以上1勝クラス見習騎手     15
2歳新馬牝             13
4歳以上1000万下        13
4歳以上2勝クラス         12
3歳未勝利牝            11
4歳オープン牝           10
4歳以上1600万下        10
2歳1勝クラス            9
4歳以上オープン牡・牝        8
4歳オープン牡・牝          8
3歳以上2勝クラス牝         8
4歳以上1勝クラス牝         7
3歳500万下            5
3歳1勝クラス            5
3歳新馬牝              4
障害4歳以上未勝利          4
3歳以上オープン牡・牝        4
4歳以上500万下          2
3歳以上1000万下牝        2
4歳以上2勝クラス牝         2
3歳500万下牝           1
4歳以上1000万下牝        1
5歳以上オープン           1
3歳1勝クラス牝           1
Name: 条件, dtype: int64

In [15]:
df["条件"] = df["条件"].str.replace("牡・牝", "")

In [16]:
df["条件"] = df["条件"].str.replace("牝", "")

In [17]:
df["条件"].value_counts()

3歳以上オープン         918
4歳以上オープン         774
3歳オープン           607
2歳オープン           237
2歳未勝利            220
3歳以上1勝クラス        168
障害3歳以上オープン       139
2歳新馬             113
障害4歳以上オープン        79
3歳以上1000万下        69
4歳オープン            60
3歳未勝利             59
3歳以上2勝クラス         53
3歳以上1600万下        53
4歳以上1勝クラス         39
2歳500万下           24
3歳以上500万下         22
障害3歳以上未勝利         21
3歳新馬              20
3歳以上1勝クラス見習騎手     15
4歳以上2勝クラス         14
4歳以上1000万下        14
4歳以上1600万下        10
2歳1勝クラス            9
3歳1勝クラス            6
3歳500万下            6
障害4歳以上未勝利          4
4歳以上500万下          2
5歳以上オープン           1
Name: 条件, dtype: int64